### ISSUE TITLE
Print History Plugin (0.4) stopped working

### ISSUE THREAD

**Issue by tonyphoang** [imrahil/OctoPrint-PrintHistory#10]
I originally installed Print History Plugin (0.4) from the Plugin Manager and everything worked then one day when I went to the History tab no data showed up.

Uninstalled Print History from the Plugin Manager and rebooted
opened up terminal
```
source ~/oprint/bin/activate
cd ~/OctoPrint
git pull & git checkout devel
python setup.py clean
 python setup.py install
pip install https://github.com/imrahil/OctoPrint-PrintHistory/archive/master.zip
sudo service octoprint restart
```

Tried it again but no success. History tab opens but no data shows on the tab even after I printed some things

![screen shot 2015-06-14 at 5 42 23 pm](https://cloud.githubusercontent.com/assets/12704968/8150573/d3e7d9b4-12bc-11e5-8e7d-4a70e7e28b19.png)

**Comment by imrahil** [comment]
all history data are stored in file *history.yaml* under *uploads* folder
check this file please

**Comment by tonyphoang** [comment]
pi@octopi ~/.octoprint/uploads $ cat history.yaml 
0:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: rpi_camera.gcode
  note: ''
1433799364477:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: rpi_camera.gcode
  note: ''
  printTime: 2019.9974520206451
  success: true
  timestamp: 1433799364.477017
1433800513702:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: rpi_camera2.gcode
  note: ''
  success: false
  timestamp: 1433800513.702323
1433801929993:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: rpi_camera2.gcode
  note: ''
  printTime: 1369.3485350608826
  success: true
  timestamp: 1433801929.993082
1433805467298:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: raspberri_pi_camera_case.gcode
  note: ''
  printTime: 3005.2027390003204
  success: true
  timestamp: 1433805467.298832
1433816712642:
  fileName: Feet2.gcode
  note: ''
  printTime: 9640.595685958862
  success: true
  timestamp: 1433816712.6425
1433888939778:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: Pi_Camera_Mount_Cover_no.gcode
  note: ''
  printTime: 1896.441223859787
  success: true
  timestamp: 1433888939.778049
0:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: sitting.gcode
  note: ''
1433895446141:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: sitting.gcode
  note: ''
  success: false
  timestamp: 1433895446.141886
1433896719029:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: sitting.gcode
  note: ''
  printTime: 1133.6998569965363
  success: true
  timestamp: 1433896719.029484
1433897410832:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: case_rear.gcode
  note: ''
  printTime: 668.1837711334229
  success: true
  timestamp: 1433897410.832718
1433898719643:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: climbing.gcode
  note: ''
  printTime: 926.0221619606018
  success: true
  timestamp: 1433898719.643407
1433899936629:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: climbing.gcode
  note: ''
  printTime: 919.1080961227417
  success: true
  timestamp: 1433899936.629306
1433900670367:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: climbing.gcode
  note: ''
  printTime: 919.1080961227417
  success: false
  timestamp: 1433900670.36769
1433900670367:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: climbing.gcode
  note: ''
  printTime: 919.1080961227417
  success: false
  timestamp: 1433900670.36769
1433901451052:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: climbing.gcode
  note: ''
  printTime: 919.1080961227417
  success: false
  timestamp: 1433901451.052756
1433901461684:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: climbing.gcode
  note: ''
  printTime: 919.1080961227417
  success: false
  timestamp: 1433901461.684078
1433901461684:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: climbing.gcode
  note: ''
  printTime: 919.1080961227417
  success: false
  timestamp: 1433901461.684078
1433902453106:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: climbing.gcode
  note: ''
  printTime: 919.1080961227417
  success: false
  timestamp: 1433902453.106601
1433902929645:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: climbing.gcode
  note: ''
  printTime: 919.1080961227417
  success: false
  timestamp: 1433902929.645899
1433903332040:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: climbing.gcode
  note: ''
  printTime: 919.1080961227417
  success: false
  timestamp: 1433903332.04001
1433903482054:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: climbing.gcode
  note: ''
  printTime: 919.1080961227417
  success: false
  timestamp: 1433903482.054229
1433903879545:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: climbing.gcode
  note: ''
  printTime: 919.1080961227417
  success: false
  timestamp: 1433903879.545435
1433904212901:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: climbing.gcode
  note: ''
  printTime: 919.1080961227417
  success: false
  timestamp: 1433904212.901859
1433904421896:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: climbing.gcode
  note: ''
  printTime: 919.1080961227417
  success: false
  timestamp: 1433904421.896533
1433905502868:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: climbing.gcode
  note: ''
  printTime: 924.8091561794281
  success: true
  timestamp: 1433905502.868245
1433906573611:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: climbing.gcode
  note: ''
  printTime: 754.24707198143
  success: true
  timestamp: 1433906573.61157
1433957587940:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: climbing.gcode
  note: ''
  printTime: 920.6585509777069
  success: true
  timestamp: 1433957587.940405
1433962933056:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: standing.gcode
  note: ''
  printTime: 959.3558230400085
  success: true
  timestamp: 1433962933.056474
1433965150053:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: standing.gcode
  note: ''
  printTime: 899.5344779491425
  success: true
  timestamp: 1433965150.053549
1433965973796:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: climbing.gcode
  note: ''
  printTime: 816.9317760467529
  success: true
  timestamp: 1433965973.796622
1433966916231:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: lying.gcode
  note: ''
  printTime: 915.4712040424347
  success: true
  timestamp: 1433966916.231412
1433968323269:
  filamentLength: 0.0
  filamentVolume: 0.0
  fileName: rpi_mount.gcode
  note: ''
  printTime: 1282.3613350391388
  success: true
  timestamp: 1433968323.269897
1433975530566:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: rpi_mount.gcode
  note: ''
  printTime: 1050.2514050006866
  success: true
  timestamp: 1433975530.566009
1433979037039:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: rpi_mount.gcode
  note: ''
  printTime: 1050.3179080486298
  success: true
  timestamp: 1433979037.039376
1433985211468:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: rpi_mount.gcode
  note: ''
  printTime: 1006.4941861629486
  success: true
  timestamp: 1433985211.468429
1433986734424:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: part3.gcode
  note: ''
  printTime: 1406.5219240188599
  success: true
  timestamp: 1433986734.424119
1433987749154:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: part4.gcode
  note: ''
  printTime: 911.9076299667358
  success: true
  timestamp: 1433987749.154385
1433995375209:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: climbing.gcode
  note: ''
  printTime: 816.9317760467529
  success: false
  timestamp: 1433995375.209813
1433996487091:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: climbing.gcode
  note: ''
  printTime: 925.1278591156006
  success: true
  timestamp: 1433996487.091524
1434027803445:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: sitting.gcode
  note: ''
  success: false
  timestamp: 1434027803.445022
1434029562322:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: sitting.gcode
  note: ''
  printTime: 1124.0667300224304
  success: true
  timestamp: 1434029562.322702
1434030837142:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: climbing.gcode
  note: ''
  printTime: 754.6972169876099
  success: true
  timestamp: 1434030837.142003
1434032977963:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: climbing.gcode
  note: ''
  printTime: 921.2122840881348
  success: true
  timestamp: 1434032977.963278
1434033602660:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: part3.gcode
  note: ''
  printTime: 1406.5219240188599
  success: false
  timestamp: 1434033602.660817
1434033920460:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: part3.gcode
  note: ''
  printTime: 1406.5219240188599
  success: false
  timestamp: 1434033920.46034
1434036964737:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: part3.gcode
  note: ''
  printTime: 1406.5219240188599
  success: false
  timestamp: 1434036964.737918
1434037356868:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: lying.gcode
  note: ''
  printTime: 915.4712040424347
  success: false
  timestamp: 1434037356.868722
1434037545674:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: standing.gcode
  note: ''
  printTime: 899.5344779491425
  success: false
  timestamp: 1434037545.674208
1434037739475:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: standing.gcode
  note: ''
  printTime: 899.5344779491425
  success: false
  timestamp: 1434037739.475157
1434037790325:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: sitting.gcode
  note: ''
  printTime: 1124.0667300224304
  success: false
  timestamp: 1434037790.325588
1434037922624:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: climbing.gcode
  note: ''
  printTime: 921.2122840881348
  success: false
  timestamp: 1434037922.624195
1434057666258:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: climbing.gcode
  note: ''
  printTime: 941.6509101390839
  success: true
  timestamp: 1434057666.25837
1434058613935:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: climbing.gcode
  note: ''
  printTime: 941.6509101390839
  success: false
  timestamp: 1434058613.935564
1434059741534:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: climbing.gcode
  note: ''
  printTime: 933.221107006073
  success: true
  timestamp: 1434059741.534646
1434060716124:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: standing.gcode
  note: ''
  printTime: 900.3680648803711
  success: true
  timestamp: 1434060716.124171
1434061878702:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: sitting.gcode
  note: ''
  printTime: 1062.8729529380798
  success: true
  timestamp: 1434061878.702312
1434067944913:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: climbing.gcode
  note: ''
  printTime: 943.1911671161652
  success: true
  timestamp: 1434067944.913691
1434075319057:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: filament_guide.gcode
  note: ''
  printTime: 1524.6495270729065
  success: true
  timestamp: 1434075319.057696
1434125254539:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: filament_guide.gcode
  note: ''
  printTime: 1419.4519548416138
  success: true
  timestamp: 1434125254.539578
1434127188398:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: filament_guide.gcode
  note: ''
  printTime: 1372.8104541301727
  success: true
  timestamp: 1434127188.398318
1434143030746:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: climbing.gcode
  note: ''
  printTime: 943.1911671161652
  success: false
  timestamp: 1434143030.746706
1434143152651:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: filament_guide.gcode
  note: ''
  printTime: 1372.8104541301727
  success: false
  timestamp: 1434143152.651881
1434148810125:
  fileName: test1.gcode
  note: ''
  success: false
  timestamp: 1434148810.125295
1434150841653:
  fileName: test1.gcode
  note: ''
  printTime: 1783.4042038917542
  success: true
  timestamp: 1434150841.653969
0:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: test2.gcode
  note: ''
1434151171532:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: filament_guide.gcode
  note: ''
  printTime: 1372.8104541301727
  success: false
  timestamp: 1434151171.532682
1434157270243:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: fan.gcode
  note: ''
  printTime: 5955.701809167862
  success: true
  timestamp: 1434157270.243506
1434171686066:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: camera_arm.gcode
  note: ''
  success: false
  timestamp: 1434171686.066891
1434178359909:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: camera_arm.gcode
  note: ''
  printTime: 5259.55664896965
  success: true
  timestamp: 1434178359.90948
1434252652144:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: wedge.gcode
  note: ''
  printTime: 865.0416460037231
  success: true
  timestamp: 1434252652.144214
1434255386689:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: filament_guide.gcode
  note: ''
  printTime: 1372.8104541301727
  success: false
  timestamp: 1434255386.689871
1434255660873:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: filament_guide.gcode
  note: ''
  printTime: 1372.8104541301727
  success: false
  timestamp: 1434255660.873212
1434256031475:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: filament_guide.gcode
  note: ''
  printTime: 1372.8104541301727
  success: false
  timestamp: 1434256031.47528
1434262473001:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: ActiveDuctD4_UN.gcode
  note: ''
  printTime: 4873.689257144928
  success: true
  timestamp: 1434262473.001729
1434276945402:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: Part2.gcode
  note: ''
  printTime: 869.3251528739929
  success: true
  timestamp: 1434276945.402445
1434280258415:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: Part3.gcode
  note: ''
  printTime: 2925.7522900104523
  success: true
  timestamp: 1434280258.415706
1434295375789:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: imperial_mickey.gcode
  note: ''
  printTime: 9840.334886074066
  success: true
  timestamp: 1434295375.789123
1434342292355:
  filamentLength: 25.0
  filamentVolume: 0.0
  fileName: dragon.gcode
  note: ''
  printTime: 19185.7854180336
  success: true
  timestamp: 1434342292.355178

**Comment by tonyphoang** [comment]
Trying to uninstall the plugin with plugin manager gives me this error
```

Uninstalling plugin "Print History Plugin"
Not uninstalling OctoPrint-PrintHistory at
/usr/local/lib/python2.7/dist-packages, outside environment
/home/pi/oprint
Done!

```

**Comment by imrahil** [comment]
Hi! 
1. Try to update to latest OctoPrint and latest version of PrintHistory plugin.
2. is your history.yaml without indentation? it clearly wrong...
