### ISSUE TITLE
Deleting a print from history causes list to resort

### ISSUE THREAD

**Issue by pauly7300** [imrahil/OctoPrint-PrintHistory#13]
Regardless of the beginning sort order, when i pressing to delete an entry, the record is deleted however the list resorts into a pattern that doesn't appear obvious.  See screenshots 1 (pre-delete) and 2 (after deletion).

In addition,although likely a separate defect, if i delete a record while a print is in progress, the printer pauses on and off for ~3-5 seconds while the deletion is being processed.

I'm on a Pi2
latest Dev build of Octoprint (1.3.0 dev95...) but i have seen this behavior even prior to the 1.2 upgrade.
Running 0.6 version of print history

![screenshot1](https://cloud.githubusercontent.com/assets/11494052/8639800/ba38930c-28a9-11e5-8dd8-4af39b1ff9a6.png)
![screenshot2](https://cloud.githubusercontent.com/assets/11494052/8639801/bd183082-28a9-11e5-9443-2f92eb3174f0.png)

**Comment by imrahil** [comment]
my fault - file operations should be prohibited during printing

**Comment by pauly7300** [comment]
ok thanks.  That's on the deletion...  Is the sorting a different issue?
