### ISSUE TITLE
Octoprint serial stutters while loading a new web ui instance

### ISSUE THREAD

**Issue by Mikk36** [imrahil/OctoPrint-PrintHistory#15]
Seems like there's somthing hogging the cpu when a new client connects to the web ui, which makes the serial connection to the printer stutter. This is especially visible when doing smooth surfaces, like circles.

**Comment by imrahil** [comment]
how it's related to PrintHistory plugin?

**Comment by Mikk36** [comment]
This only happens when I have PrintHistory plugin enabled.
