### ISSUE TITLE
Fail reason logging

### ISSUE THREAD

**Issue by FrenkK** [imrahil/OctoPrint-PrintHistory#16]
This is a feature suggestion: It would be really nice if I could select a reason for printing fail (e.g. unstuck print, hot end issue, malfunction, filament issue) and be able to see a breakdown of fail reasons in the stats. This would be best implemented by a fillable drop-down list - you click the failed print job and select an existing fail reason or add a new one. Thank you for an awesome tool! :)

**Comment by imrahil** [comment]
I think note functionality is fine for now...
