### ISSUE TITLE
History displays completed time of failed print if print passed before

### ISSUE THREAD

**Issue by geodave810** [imrahil/OctoPrint-PrintHistory#19]
Looks like the history picks up the completed time from a completed print and uses it for the time of a failed print of the same name.  Here is a screen capture of the problem.
![octoprint_historyfaileprintaddedtime](https://cloud.githubusercontent.com/assets/13069472/10194123/0467ec86-6755-11e5-9c9b-f90ac1339d51.JPG)

**Comment by Shambala001** [comment]
The plugin pulls the print time from octoprints metadata value "lastPrintTime" which is the last print time of a completed print, it doesnt store the time of failed ones. It should probably return a value of "-" instead of the last time however.

**Comment by imrahil** [comment]
fixed in 1.0.0
