### ISSUE TITLE
Track User Prints

### ISSUE THREAD

**Issue by lovesegfault** [imrahil/OctoPrint-PrintHistory#20]
It would be nice to make use of the User Access Control feature to also log which user issued which print. On a multi-user environment having something like this could be particularly useful.
@imrahil do you think this is possible?

**Comment by bastard** [comment]
I agree - it should take care of the user level as well. The user should be able to edit his entry but is not allowed to delete it.

**Comment by motzke** [comment]
I would like to see which user has printed what!

**Comment by Pinaute** [comment]
Hi @imrahil   
What file provided data Filename Date, Print time, ... ?
I'm going to try fix the issue

**Comment by danielwells** [comment]
Looks like you've already added this as an enhancement but I wanted to put in my vote for it as well.  I'd love the "user" to be added as a column in the export as well.  Thanks.

**Comment by cmtec** [comment]
+1
Seems that the main feature is already implemented (in v1.1?) but I would like that the user been added  automatically. Right now I have too guess what user did the print and manually add him/her.

**Comment by imrahil** [comment]
sorry but I can't - AFAIK there is no way to get current user data on backend side

**Comment by imrahil** [comment]
print details are provided in event handler which is run in different thread than rest of the backend... I didn't find a way how to workaround this.

**Comment by danielwells** [comment]
Has this been added as a feature request in OctoPrint core then (to get access to the user)?

**Comment by WildRikku** [comment]
> Hi @imrahil Ok. Question: is "current_user.get_name()" not accessible as a plugin?

This would not be a good solution, as a print could have been started by a different user than the current user and also a print might finish when no user is logged in.
