### ISSUE TITLE
Missing Trash Can

### ISSUE THREAD

**Issue by eboston** [imrahil/OctoPrint-PrintHistory#22]
I have version 0.7 installed but I am not seeing the Trash Can for deleting jobs from the list.

**Comment by imrahil** [comment]
trash can is visible only for logged users

**Comment by eboston** [comment]
I was logged

**Comment by imrahil** [comment]
are you able to reproduce this behaviour? did you have any errors in octoprint.log or javascript console in browser?

**Comment by eboston** [comment]
I hardly go into the tab to begin with and was only in there because a question someone had.  This was the first time I noticed the problem.  I will check and see if it happens again.
