### ISSUE TITLE
All diagrams are empty

### ISSUE THREAD

**Issue by EddyMI3d** [imrahil/OctoPrint-PrintHistory#23]
Hello!
After update to OctoPrint 1.2.7 all diagrams are empty. No more data is showen.

**Comment by eboston** [comment]
Just noticed this same problem.  I am on 1.2.8.  Removed it for now as it's not very useful if it doesn't show any information.  :(

**Comment by Mortorojo** [comment]
Having the same issue on 1.2.8.

**Comment by imrahil** [comment]
Published new version. Please test it
