### ISSUE TITLE
Lost to the history of printing.

### ISSUE THREAD

**Issue by cucpo** [imrahil/OctoPrint-PrintHistory#25]
I use plugins least two months, ever I had a lot of data, after the restart of octoprint I have set HISTORY empty. Is the ability to recover data?

**Comment by imrahil** [comment]
check your history.yaml - e.g. /home/octo/.octoprint/data/printhistory/history.yaml

**Comment by cucpo** [comment]
i have printhistory_console.log, It will not help me?
