### ISSUE TITLE
Successful Print Doesn't Include Filament Usage

### ISSUE THREAD

**Issue by ophilli** [imrahil/OctoPrint-PrintHistory#32]
I'm having an issue where an otherwise successful print doesn't include Filament length and Filament volume.

Based upon the screenshots shown at http://plugins.octoprint.org/plugins/printhistory/ that doesn't appear to be the expected case.

I have attached a screenshot detailing the unexpected behavior, as well as the associated print history excel export.

<img width="967" alt="printhistory" src="https://cloud.githubusercontent.com/assets/964870/18789630/a999c302-8179-11e6-9415-aaabf223461e.PNG">

[octoprint_print_history_export.xlsx](https://github.com/imrahil/OctoPrint-PrintHistory/files/489911/octoprint_print_history_export.xlsx)

**Comment by imrahil** [comment]
have you seen issues #18 and #27 ?
