### ISSUE TITLE
Print time blank with OctoPrint 1.3.0rc1

### ISSUE THREAD

**Issue by JohnOCFII** [imrahil/OctoPrint-PrintHistory#34]
Since upgrading OctoPrint to the latest release candidate, Print time is not displayed.  I've attached a screen shot.

![printhistory](https://cloud.githubusercontent.com/assets/7844212/19838846/95f7a3e8-9ea5-11e6-9191-8782b1466754.png)

**Comment by JohnOCFII** [comment]
Since the 0.9.1 update, times are once again displayed properly.  Closing.

**Comment by JohnOCFII** [comment]
I was too quick to close the issue.  It seemed better after 0.9.1, but after a few prints, it stopped displaying the time.  I just updated to 0.9.2, and haven't printed with it yet, but here is a current screen shot.  
![printhistory](https://cloud.githubusercontent.com/assets/7844212/21288101/15e7c80c-c440-11e6-90ea-4407106d07de.jpeg)

**Comment by imrahil** [comment]
two things: 
- just discovered that 0.9.2 isn't production ready yet :)
- could you share somehow your history.yaml file?

**Comment by JohnOCFII** [comment]
My zipped history.yaml is attached.


[history.yaml.zip](https://github.com/imrahil/OctoPrint-PrintHistory/files/659036/history.yaml.zip)

**Comment by imrahil** [comment]
Fixed in 1.0.0
