### ISSUE TITLE
Since Octoprint 1.3 Update, Print History Vanished

### ISSUE THREAD

**Issue by titelies** [imrahil/OctoPrint-PrintHistory#35]
Please help, would like to recover all my print history data since I began using this plugin back in February.  Couldn't find history.yaml 
See screenshots and log file:
http://i.imgur.com/ju1KO5U.png
http://i.imgur.com/f3JV8DI.png
https://dl.dropboxusercontent.com/u/7579452/plugin_printhistory_console.log.zip

**Comment by imrahil** [comment]
history.yaml is now history.bak (latest version migrated data to SQLite database)
but even that your history.bak is only 455 bytes size so there is no more data than these 2 records

console log isn't helpful at all :)
maybe is it possible to share your octoprint.log ?
