### ISSUE TITLE
Print time and filament usage not showing

### ISSUE THREAD

**Issue by musyne** [imrahil/OctoPrint-PrintHistory#36]
Hi,
On a fresh Octoprint 1.3 everything is working fine except as the title says. I've done 4 prints from it so far (all successful), but I only get the Date and the status of the print, no other information ("-").
Do I need to setup something?

**Comment by musyne** [comment]
New discovery: I've had a failed print and it shows the print time and filament usage. So I guess a recent commit somehow inverted the logic by mistake?

**Comment by imrahil** [comment]
you have to wait for gcode analysis if you want detailed info in history tab... see: https://github.com/imrahil/OctoPrint-PrintHistory/issues/32

**Comment by Tailslide** [comment]
I'm using the API to print directly from my slicer.. is there some way to insert a delay so the filament usage will show up?
