### ISSUE TITLE
Lost History with new History Upgrade

### ISSUE THREAD

**Issue by wmmc01** [imrahil/OctoPrint-PrintHistory#38]
Help - I completely lost all my previous History when I ran the last update to the History module. It was 10 months of printing history. Is there some way to recover that?

**Comment by imrahil** [comment]
check if you have history.bak file in .octoprint/data/printhistory

**Comment by wmmc01** [comment]
I don’t see that subdirectory anywhere.

**Comment by imrahil** [comment]
https://github.com/foosel/OctoPrint/blob/master/CONTRIBUTING.md#where-can-i-find-those-log-files-you-keep-talking-about

**Comment by wmmc01** [comment]
Sorry, what? You told me to see if I could find a history.bak file, which I do not understand how to find it - then you tell me how to find a log file?

**Comment by imrahil** [comment]
sorry. messed things... but log file could be useful too

**Comment by wmmc01** [comment]
But what about the History.bak file?

**Comment by imrahil** [comment]
if you'll find log files, history.bak should be there too (in data/printhistory folder)

**Comment by wmmc01** [comment]
I don't see those files or even the subdirectories on my PC. Or should I be looking on the SD card with the OctoPrint image in the Raspberry Pi?

**Comment by wmmc01** [comment]
Hello?

**Comment by imrahil** [comment]
sorry. can't help you

**Comment by wmmc01** [comment]
Seriously?
