### ISSUE TITLE
ProgrammingError: You did not supply a value for binding 3

### ISSUE THREAD

**Issue by JohnDoe2991** [imrahil/OctoPrint-PrintHistory#39]
Hi everyone!

Some of my Print History entries get lost due to a error in the plugin. For example:

> Traceback (most recent call last):
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/OctoPrint-1.3.0-py2.7.egg/octoprint/plugin/__init__.py", line 229, in call_plugin
>     result = getattr(plugin, method)(*args, **kwargs)
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_printhistory/__init__.py", line 118, in on_event
>     return eventHandler.eventHandler(self, event, payload)
>   File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_printhistory/eventHandler.py", line 97, in eventHandler
>     cur.execute("INSERT INTO print_history (fileName, note, filamentVolume, filamentLength, printTime, success, timestamp) VALUES (:fileName, :note, :filamentVolume, :filamentLength, :printTime, :success, :timestamp)", currentFile)
> ProgrammingError: You did not supply a value for binding 3.

Not all entries get lost, some are working properly. See the attached log file for more examples.
[octoprint.log.txt](https://github.com/imrahil/OctoPrint-PrintHistory/files/679998/octoprint.log.txt)
I cannot figure out why this is happening or how I could prevent it.

I'm using Octoprint 1.3.0 Master with Print History 1.0.0 on a Raspberry Pi B+ with my Prusa i3 MK2.
As a remote control I use the app OctoDroid on Android 7.1.1

Thanks for any help!
And happy new year!

**Comment by imrahil** [comment]
Fixed in 1.1
