### ISSUE TITLE
Cancelled Prints are not listed

### ISSUE THREAD

**Issue by kontakt** [imrahil/OctoPrint-PrintHistory#41]
Cancelled prints do not show in the print history at all, showing an incorrect 100% success rate.

**Comment by kontakt** [comment]
![Image](https://cloud.githubusercontent.com/assets/6045607/21583260/441a1276-d047-11e6-8da7-d11e3f96dd83.png)


You can see on the left hand side one print I cancelled that isn't shown in the list.

**Comment by imrahil** [comment]
any errors in log files?

**Comment by kontakt** [comment]
Looks like I am getting a few, log attached
[octoprint.log.2016-12-31.txt](https://github.com/imrahil/OctoPrint-PrintHistory/files/680229/octoprint.log.2016-12-31.txt)

**Comment by imrahil** [comment]
try version 1.1.1 please

**Comment by kontakt** [comment]
Working as expected!
