### ISSUE TITLE
Could you add Change Spool?

### ISSUE THREAD

**Issue by Vikinge** [imrahil/OctoPrint-PrintHistory#44]
Could you add option to track by spool or filament color?  I was tracking my black spool usage, but changed to white last night and now the data doesn't help me calculate how much of my spool has been used.  
Is there a way to reset all the data?  If I can't separate by spool or color?

I would want the print statistics to maintain across spools.

**Comment by Vikinge** [comment]
Pretty much same as request #7

**Comment by imrahil** [comment]
it's already implemented. Spools you can add in settings, then set the spool in particular history entry clicking small wrench icon.
What I need to add is table with summary info per spool (and/or chart)

**Comment by Vikinge** [comment]
great.  I had seen the spool option in settings but no wrench.  I think the wrench might be hidden while printing, can you confirm?

**Comment by imrahil** [comment]
yup. all buttons in my plugin are hidden during printing

**Comment by Vikinge** [comment]
got it.  I have been working my printer pretty hard, printing most of the day.  Thanks .
