### ISSUE TITLE
Add API support

### ISSUE THREAD

**Issue by kylemenigoz** [imrahil/OctoPrint-PrintHistory#8]
It would be fantastic if information from the history could be fetched via the OctoPrint API. Not sure what you'd have to do or if it's possible. I'd be interested in helping with this, if/as needed.

**Comment by imrahil** [comment]
It's already available. Whole UI is using API for data. History data are here: http://octoprint_url:5000/plugin/printhistory/history?apikey=YOUR_API_KEY
