### ISSUE TITLE
PrintHistory fails filamentvolume

### ISSUE THREAD

**Issue by tedder** [imrahil/OctoPrint-PrintHistory#80]
Version 1.2 installed on top of Octoprint 1.3.10.

I'm seeing the error previously fixed in #39, "did not supply a value for binding 3", which is the filament volume. I suspect something happened in the data shape for 1.3.10?

I can see a couple of things. First, the volume is coming across in tool1 (unsure yet, but might be because I'm using a multi-material feeder). It looks like this is set to filamentVolume2, which is never touched after being set.

Second, there's no tool0, so filamentVolume is never set (it doesn't touch the 'else' condition).

Third, the MetadataAnalysisFinished call returns a data shape of root->result->filament->tool1->volume. I'm noting "result" doesn't match root->analysis.

**Comment by SirBastol** [comment]
filament used is not calculated properly on failed prints
