### ISSUE TITLE
Is this plugin still maintained?

### ISSUE THREAD

**Issue by justin-chandra** [imrahil/OctoPrint-PrintHistory#93]
@guysoft Is this plugin being maintained?

There has been some longstanding issues with history export and I have made a pull request that attempts to fix those issues.

You can see my PR here: https://github.com/imrahil/OctoPrint-PrintHistory/pull/92

If you do not want to maintain this plugin anymore I would be happy to help out.

**Comment by guysoft** [comment]
It is, though I've been pretty busy lately. 
I can take a look now and thanks for the heads up.
