### ISSUE TITLE
No thumbnail in history list if spaces/accents in filename

### ISSUE THREAD

**Issue by PyBonnetainNesterenko** [imrahil/OctoPrint-PrintHistory#98]
Hello,
The plugin works great, but the thumbnails are not displayed if the printed filename contains (at least) spaces and accents. Which is annoying.

Fist with accents :
![Shutter_009](https://github.com/imrahil/OctoPrint-PrintHistory/assets/35917592/b973fb05-5279-4c35-a705-1d9629d03294)

A proper display and print :
![Shutter_010](https://github.com/imrahil/OctoPrint-PrintHistory/assets/35917592/cc849026-7ee4-406e-a766-2a651b83c6a7)

Renamed the previous file to add some spaces (and printed/canceled it, it's only to show the problem) :
![Shutter_012](https://github.com/imrahil/OctoPrint-PrintHistory/assets/35917592/30f4a3ef-26f8-41de-a078-03e8a2fabd2e)

**Comment by guysoft** [comment]
Wrong issue tracker, you want the OctoPrint-PrintJobHistory plugin, this is the OctoPrint-PrintHistory plugin.

https://github.com/OllisGit/OctoPrint-PrintJobHistory

This one sadly has no picture support.

**Comment by PyBonnetainNesterenko** [comment]
Sorry for the mistake. Must be old age setting in.

**Comment by guysoft** [comment]
I hope not, happend to me too a few years back😅
https://github.com/OllisGit/OctoPrint-PrintJobHistory/issues/68#issuecomment-667654896
